# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Common Mod Properties
mavenGroup=dev.moongarden

# Allium Properties
alliumVersion=0.5.0
alliumReleaseCandidate=0
alliumBaseName=allium

# Bouquet Properties
bouquetVersion=0.3.0
bouquetReleaseCandidate=0
bouquetBaseName=bouquet

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraftVersion=26.2-snapshot-3
loaderVersion=0.18.4
loomVersion=1.16-SNAPSHOT

# Common Dependencies
cobalt=0.9.7
enhancedReflections=0.1.6

# Non-bundled Allium dependencies
combine=2.3.0-rc.2

# Bouquet Example Script Dependencies
fabricApi=0.146.1+26.2